### ISSUE TITLE
Modify files in src?

### ISSUE THREAD

**Issue by cg-roling** [ionic-team/trapeze#107]
I'm not sure if this would be in scope for the project or not, but we have a situation where we would like to modify some files in the `src` folder of our project.

We are creating separate app IDs for dev, qa, and release builds, with their own icons. Trapeze + capacitor-assets works great for this.

However, we have a custom URL scheme for Android that we also need to change per build type, and we need to have that URL in our source code.

Right now we are using an ugly hack to get it done with Trapeze, but we'd prefer a more "official" way:

```
platforms:
  ios:
    bundleId: $BUNDLE_ID
    displayName: $DISPLAY_NAME
    # NOTE: Not actually iOS specific below here
    # It's a hack to get the custom url scheme visible to the app
    json:
      - file: ../../src/app-info.json
        merge:
          customUrlScheme: $BUNDLE_ID
```

**Comment by mlynch** [comment]
I see, so more of a non-platform tied command? Need to think about it but seems reasonable

**Comment by mlynch** [comment]
Added support for `xml` and `json` operations at the root of the project. See https://trapeze.dev/docs/configuration-tool#project for more info on how to use this.

**Comment by cg-roling** [comment]
That's awesome, this will be super helpful, thanks Max!
