### ISSUE TITLE
add docs about lunch different config files 

### ISSUE THREAD

**Issue by reslear** [ionic-team/trapeze#108]
I find in example different configs https://github.com/ionic-team/trapeze/tree/main/examples/capacitor-app but don't find in `package.json` script how to lunch this.

so i'm suggest add to documentation information about using different config, and link
https://ionic.io/docs/appflow/quickstart/environment#example-customizing-the-build-script

or is use dotenv-cli for example:

we have two file `config.dev.yml` and `config.prod.yml`

```bash
dotenv -c development -- bash -c 'npx trapeze run config-${BUILD_ENV}.yml -y'
```

**Comment by mlynch** [comment]
Just follow the configuration tool docs to see how to run it with different config files. We could certainly add more complex examples that use things like dotenv but the basic command takes any arbitrary env file, and managing those for versions is beyond the scope of this tool and ends up running up against opinionated tooling which we don't want to dictate
