### ISSUE TITLE
If iOS buildNumber is not defined, trapeze breaks pbxproj file

### ISSUE THREAD

**Issue by RaddishIoW** [ionic-team/trapeze#118]
As I found out to my cost just now, if for some reason you pass an empty string as `buildNumber` in your iOS config, it breaks the project.pbxproj file in the Xcode Project.

**Comment by mlynch** [comment]
Thanks for the report, will see about getting this fixed for you

**Comment by mlynch** [comment]
Fixed in 5.0.8
