### ISSUE TITLE
Info.plist character replace

### ISSUE THREAD

**Issue by aktivdigital-frontend** [ionic-team/trapeze#127]
Hi!

I set app name with space characters in config.yaml. For example: "My App" (there is space character)
iOs remove space characters from application name, but there is a workaround solution.

It needed add `&#x2007;` instead of space charaters. So the name will this: "My`&#x2007;`App"

But when I run config.yaml, it makes this in Info.plist: 

```
<key>CFBundleDisplayName</key>
<string>My&amp;#x2007;App</string>
```

So `&` will be `&amp;`

This is not good. There is any solution to this? Thank you!

**Comment by YadrovSergey** [comment]
I have the same problem.

**Comment by mlynch** [comment]
Can you show me the yaml you're writing in Trapeze that isn't working?

**Comment by trinitiwowka** [comment]
I have a similar problem. Could you make a fix? my application name consists only of numbers, I get a runtimeError. 
I get
`	<key>CFBundleDisplayName</key>
	<integer>1999</integer>`

but need 
`	<key>CFBundleDisplayName</key>
	<string>1999</string>`

<img width="371" alt="image" src="https://user-images.githubusercontent.com/8225740/207052511-c92ed42a-3bfa-44c2-a624-69c923e05d9b.png">
When $APP_NAME = '1999'

**Comment by mlynch** [comment]
Okay thanks, I think I'm going to have to add metadata to the vars fields to specify types

**Comment by mlynch** [comment]
Out now in 7.0.3 https://trapeze.dev/docs/Operations/getting-started#variable-types
