### ISSUE TITLE
Android/Gradle: Package attribute in manifest file is deprecated

### ISSUE THREAD

**Issue by jaufgang** [ionic-team/trapeze#143]
The `package` attribute in manifest file has been deprecated in favour of using the `namespace` property in the module-level `build.gradle`.  See https://developer.android.com/studio/releases/gradle-plugin#package-deprecated for more info.

Trapeze will need to be updated to support this change.  

Note that this issue is related to #109, as this change was the underlying cause of the error reported in that issue.  I added a comment (https://github.com/ionic-team/trapeze/issues/109#issuecomment-1338142743) to that ticket last week but it appears not to have been noticed because that issue was closed, so I'm posting a fresh issue here.

**Comment by mlynch** [comment]
So it sounds like this only applies if your gradle plugin version is 7.3.0-alpha04, or above, right. I'm going to check the version and only do it above that

**Comment by jaufgang** [comment]
Yeah, 7.3.0-alpha04 and above will suggest you migrate but doesn't require it, so you can't assume all projects with latest Gradle will have changed. I think it will be necessary to look in secondary location if it's not found in the first one you check, in whichever order.

**Comment by mlynch** [comment]
Sounds good, just going to set them both for now

**Comment by mlynch** [comment]
Out in 7.0.0. Will just set both for now but will prioritize the `namespace` field when reading
