### ISSUE TITLE
Add newly created files to pbxproj

### ISSUE THREAD

**Issue by mlynch** [ionic-team/trapeze#144]
When we create new files (see #116) we need to make sure those get added to the actual `pbxproj`

**Comment by mlynch** [comment]
Added in #144

**Comment by vscaiceanu-1a** [comment]
Hi @mlynch 

I created a tiny project to reproduce the issue https://github.com/victorsc/trapeze-issues

Running trapeze doesn't really update [ios/App/App.xcodeproj/project.pbxproj](https://github.com/victorsc/trapeze-issues/compare/main...issue/144#diff-daf8b4afd54ea846a9a196d9d428c052957b96c0f10520c88ee07c018194321f)

Manually adding in Xcode the two files
* [ios/App/App/de.lproj/InfoPlist.strings](https://github.com/victorsc/trapeze-issues/compare/main...issue/144-expected#diff-6a22945dae537be76c6e7b21ce80b959098d6ff256e4abfbddad7e71365df2a9)
* [ios/App/App/en.lproj/InfoPlist.strings](https://github.com/victorsc/trapeze-issues/compare/main...issue/144-expected#diff-f7eda8186690eacd2be9f78f0ec3be37f3cae4e22a34668da17611a6d8001139)

I get this [ios/App/App.xcodeproj/project.pbxproj](https://github.com/victorsc/trapeze-issues/compare/main...issue/144-expected#diff-daf8b4afd54ea846a9a196d9d428c052957b96c0f10520c88ee07c018194321f)

**Comment by mlynch** [comment]
Thanks, let me double check something, it's possible the actual pbx project isn't getting committed 🤦🏻

**Comment by mlynch** [comment]
Okay I've found the issue: if the file is added during the commit phase, it's possible the commit phase for the `pbxproj` already ran so the changes won't be reflect. Basically a race condition. I'll fix this tomorrow

**Comment by mlynch** [comment]
@vscaiceanu-1a try 7.0.2. Fixed the issue adding the file to the project and made a change to support paths and how they correspond to the Group concept inside of xcode projects

**Comment by vscaiceanu-1a** [comment]
hi @mlynch.
Works like a charm.
Thank you so much!

**Comment by mlynch** [comment]
Awesome, I might want to add the support later for customizing where the files get added, the approach is simple currently
