### ISSUE TITLE
A way to offset $CI_BUILD_NUMBER

### ISSUE THREAD

**Issue by benmarsh** [ionic-team/trapeze#161]
I use AppFlow and I'm keen to use Trapeze to automatically update build number each time a build is run.

My issue is that our manually entered build numbers started at 10000 and the AppFlow $CI_BUILD_NUMBER is currently in the thousands range. As Apple require the build numbers to increase with each submission this would cause an issue.

Possibly this is an AppFlow question (or maybe a broader YAML question) but is there a way to either offset the $CI_BUILD_NUMBER by say (in this particular instance) adding 20000 to it, or a way to set a new starting number based on our last used manual build number?

Thanks!

**Comment by mlynch** [comment]
You're in luck, we have that in the auto-incrementing cookbook for Appflow. In this case you just apply the offset to the env var before using it: https://ionic.io/docs/appflow/cookbook/auto-incrementing-build-numbers#setting-initial-build-number

Hope that helps!

**Comment by benmarsh** [comment]
Brilliant, thanks Max 👍🏼
