### ISSUE TITLE
Bug: Incompatible with latest Capacitor V5 Android Platform

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/trapeze#185]
## Description

As of Capacitor v5 the Android project structure seems to have changed.
The `MainActivity.java` file is not located where it formerly was.

Trapeze expects the file under this path: `android/app/src/main/java/MainActivity.java`

But now it's located under `android/app/src/main/java/io/ionic/starter/MainActivity.java`. 

Therefore, running `npx @trapezedev/configure run platform-config.yml` results in the following error:

![image](https://user-images.githubusercontent.com/1294854/236482493-720e0a36-4225-4321-abfe-c7d5245c664a.png)

## Versions

- Trapeze: `7.0.8`
- Capacitor: `5.0.0`
- macOS: `Ventura - 13.3.1 (a)`

## Reproduction

For reproduction purposes I've created a pristine demo repository with a blank ionic app and only an android platform.

1. Clone Repo: https://github.com/tobiasmuecksch/cap5-trapeze-bug
2. Install dependencies `npm i`
3. run `npx @trapezedev/configure run platform-config.yml`
4. See the error

**Comment by martinbertinat** [comment]
Same problem here.

Did you found a workaround?

Thanks

**Comment by tobiasmuecksch** [comment]
@martinbertinat No. I haven't.

**Comment by mlynch** [comment]
Thanks will look into this. Regardless it shouldn't assume and should either support it being specified or read it from the manifest (ideally)

**Comment by mlynch** [comment]
Fixed in 7.0.9

**Comment by tobiasmuecksch** [comment]
@mlynch Thank you so much, for the quick fix. I've tested it, and it works like a charm!

**Comment by tobiasmuecksch** [comment]
@mlynch I'm afraid I have to revoke what I said. It doesn't work as expected. After running trapeze Android Studio cannot start the app in the emulator anymore.

Since I cannot reopen this issue, I have opened a new one here: https://github.com/ionic-team/trapeze/issues/188
