### ISSUE TITLE
Bug: Incompatible with latest Capacitor V5 Android Platform

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/trapeze#188]
## Description

Since I cannot reopen https://github.com/ionic-team/trapeze/issues/185, I'm creating this new issue.

After running `npx @trapezedev/configure run platform-config.yml` (Version 7.0.9, I double checked that) Android Studio isn't able to start the app anymore and shows the following error:

<img width="1506" alt="Bildschirmfoto 2023-05-09 um 11 11 34" src="https://user-images.githubusercontent.com/1294854/237050483-d9e32a20-925c-4ead-bfc6-3f2484ee33d5.png">

I assume this bug was introduced while fixing https://github.com/ionic-team/trapeze/issues/185.

## Reproduction 

1. Clone Repo: https://github.com/tobiasmuecksch/cap5-trapeze-bug
2. Install dependencies `npm i` 
3. run `ionic cap sync`
4. run `npx @trapezedev/configure run platform-config.yml`
5. run `ionic cap open android`
6. Start the app in an emulator
7. See the aforementioned error

**Comment by tobiasmuecksch** [comment]
I assume that this particular spot is where things are going wrong:

<img width="1499" alt="Bildschirmfoto 2023-05-09 um 11 06 42" src="https://user-images.githubusercontent.com/1294854/237054182-f51c670c-57b2-49a9-a390-498a1594da42.png">

But I don't know where this is coming from. I've search-and-replaced all occurrences of "io.ionic.starter" but this issue still persists.

**Comment by mlynch** [comment]
I wonder if this is because it's setting some additional manifest fields that aren't expected. I'll double check and improve my tests

**Comment by mlynch** [comment]
Can you try `@trapezedev/configure@next`? It won't add any more package info to the manifest if there wasn't any there before and will only change the gradle `applicationId` and `namespace`

**Comment by mlynch** [comment]
Did you make sure the changes from the last run were undone first? I will be able to test it again later once i'm back on better internet

**Comment by tobiasmuecksch** [comment]
I'm 100% sure. I've rolled back all changes and double checked that by starting the app in the emulator (which worked). Afterwards I re-ran trapeze and restarted the emulator - the error was back.

**Comment by mlynch** [comment]
I just tested it, ran into the same issue, and fixed it by invalidating caches and restarting. This appears to just be a bug with android studio caching and not an issue with the tool

**Comment by WillPoulson** [comment]
For anyone running into these issues with the `@trapezedev/project` package, installing `7.0.10-next.0` resolve the issue for me as Max suggested above 😄.

This issue just saved me an hour or two debugging. Thanks guys!

**Comment by mlynch** [comment]
Sounds like this is working fine then so I'll ship a new `latest`

**Comment by tobiasmuecksch** [comment]
@mlynch Yes, I can also confirm it does. Thank you very much! 😃

**Comment by mlynch** [comment]
7.0.10 is live with this fixed
