### ISSUE TITLE
info.plist auto generated is not defined?

### ISSUE THREAD

**Issue by reslear** [ionic-team/trapeze#45]

**Comment by reslear** [comment]
<img width="631" alt="Screenshot 2022-02-08 at 02 54 44" src="https://user-images.githubusercontent.com/12596485/152891980-0f390fd6-b5e6-4eda-82d9-0a76e073ad87.png">

> info.plist auto generated is not defined?

check - No.

so, maybe need create default Info.plist like Entitlements:

https://github.com/ionic-team/capacitor-configure/blob/ae52941f1b2c390ed377f47a80153aea207afcc6/packages/project/src/ios/project.ts#L11-L18

**Comment by mlynch** [comment]
Interesting. Was this on a fresh Capacitor project?

**Comment by reslear** [comment]
hi @mlynch yes, what do you think about this?

**Comment by mlynch** [comment]
I may have fixed this. Will take a look next week most likely
