### ISSUE TITLE
Replacing ios app entitlements with YAML

### ISSUE THREAD

**Issue by sanderschnydrig** [ionic-team/trapeze#51]
Hi Max!

I thought it would be nice if we can replace the ios entitlements that have multiple values. The way I'm doing this now is combined with the Typescript approach:
`capacitor.ts`
```typescript
  const project: CapacitorProject = new CapacitorProject(config)
  await project.load()

  const appTarget = project.ios?.getAppTarget()
  const targetName = appTarget.name
  const buildName: IosBuildName = `Release` // Release, Debug or null

  // clean entitlements
  const entitlements = await project.ios?.getEntitlements(targetName, buildName)
  delete entitlements[`com.apple.developer.associated-domains`]

  // commit changes
  await project.commit()
```
`capacitor.yaml`
```yaml
entitlements:
          - com.apple.developer.associated-domains:
              [
                'applinks:$BASE_URL',
                'applinks:$NEWSAPP_PAGE_LINK',
              ]
```

and execute them in this order:
```console
npx tsc configuration/capacitor.ts && node configuration/capacitor.js
npx @capacitor/configure@2.0.3 run configuration/capacitor.yaml -y
```

Maybe the inject / replace approach from the gradle file would work here as well.

I don't think I'd be able to contribute to the repo at this stage but I'll be happy to test any functionality that you decide to have a crack at. Best regards

**Comment by mlynch** [comment]
Meaning instead of adding them to the array you want to blow the array away and set it to those specific values? That should be pretty easy to do

**Comment by sanderschnydrig** [comment]
@mlynch Exactly. We are currently replacing those values for whitelabelling our app in regards to Deep Links / Dynamic Links, so being able to do it all in the YAML would be pretty neat.

**Comment by vcomperq** [comment]
Hi @mlynch,
i expect the same behavior  as @sanderschnydrig .

could it be possible to have that in a next version ? 

Thanks

**Comment by mlynch** [comment]
Yep just added support for this, will land shortly.

**Comment by mlynch** [comment]
Available in 3.0.7 https://trapeze.dev/docs/configuration-tool#entitlements

**Comment by DavidStrausz** [comment]
@mlynch There is still an issue in the `createOpDisplayText` function in case the `entitlements` config is an object:

```shell
[error] Unable to load config file: op.value.map is not a function
Fatal error: Error running command
TypeError: op.value.map is not a function
    at createOpDisplayText (/Users/path/to/project/node_modules/@trapezedev/configure/dist/op.js:145:29)
    at createIosOperation (/Users/path/to/project/node_modules/@trapezedev/configure/dist/op.js:95:22)
    at /Users/path/to/project/node_modules/@trapezedev/configure/dist/op.js:58:24
    at Array.map (<anonymous>)
    at createIosPlatformTarget (/Users/path/to/project/node_modules/@trapezedev/configure/dist/op.js:58:14)
    at /Users/path/to/project/node_modules/@trapezedev/configure/dist/op.js:49:24
    at Array.map (<anonymous>)
    at createIosPlatformTargets (/Users/path/to/project/node_modules/@trapezedev/configure/dist/op.js:49:10)
    at createIosPlatform (/Users/path/to/project/node_modules/@trapezedev/configure/dist/op.js:33:16)
    at createPlatform (/Users/path/to/project/node_modules/@trapezedev/configure/dist/op.js:16:16)
```

In this case you want to map `op.value.entries` array, not the `op.value` object.

**Comment by mlynch** [comment]
Actually looks like it just needs to support the two different formats to this command, will fix

**Comment by mlynch** [comment]
This will land in the next release this week
