### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by co-dax** [ionic-team/trapeze#68]
Hi @mlynch could you please provide an example of tsconfig.json and package.json files to run the project?
I tried a lot of combinations with fields module, target, moduleResolution, esModuleInterop, "type": "module" in package.json, etc... and there is always so error.
I checked this repository but it could only find basic.yml file in "examples" folder.

Thanks!

**Comment by mlynch** [comment]
I'm not following. There shouldn't be any need for an example project. What errors are you getting?

**Comment by cosic-dalibor** [comment]
I was trying to run example commands from page [https://github.com/ionic-team/capacitor-configure](url):

`await project.ios?.setVersion('App', 'Debug', '1.4.5');
await project.ios?.incrementBuild('App');
project.ios?.getBuild('App', 'Debug');
project.ios?.getBuild('App', 'Release');
await project.android?.setVersionName('1.0.2');
await project.android?.getVersionName();
await project.android?.setVersionCode(11);
await project.android?.getVersionCode();
await project.android?.incrementVersionCode();`

...and I was getting errors when trying to run that script from above. I eventually managed to fix it by setting

1.  "type": "module" in package.json, 
2. "esModuleInterop": true in tsconfig.json
3. "target": "es2017" in tsconfig.json
4. "module": "es2022" in tsconfig.json

It took me quite a bit to hit the exact combination.


I agree it is not anything wrong with the project itself but it may be useful for others when starting.

**Comment by mlynch** [comment]
There's an example now in https://github.com/ionic-team/trapeze/tree/main/examples/project-api-example, hope it helps

**Comment by co-dax** [comment]
@mlynch Great, thanks! I will try it and come back if there is any issue.
