### ISSUE TITLE
Can't install @trapezedev/configure & @trapezedev/project

### ISSUE THREAD

**Issue by AliMejbar** [ionic-team/trapeze#71]
Hi,
Yarn and NPM can't find the packages , also the readme has mixed parts of both old package name and the new rebranding which is a bit confusing.

![image](https://user-images.githubusercontent.com/55496459/173207994-2d2fc239-2f88-4b36-8bef-58299d819cfd.png)

**Comment by mlynch** [comment]
Still a work in progress, thanks. Should be fixed this week
