### ISSUE TITLE
Question (Android Manifest): How can I add a new attribute to the <application> tag? 

### ISSUE THREAD

**Issue by alexconstantin** [ionic-team/trapeze#89]
Hello,

I am trying to add this tag: `android:usesCleartextTraffic="true"` to the existing `<application>` tag, under the `<manifest>`
I tried using `project.android?.getAndroidManifest().find('application')` but this returns an empty array.

How should we approach this?
Thank you!

**Comment by mlynch** [comment]
Make sure you called `project.load()` first and awaited the result.

I have this in the tests and it's working fine:

```typescript
    project.android?.getAndroidManifest().setAttrs('manifest/application', {
      'android:name': 'com.ionicframework.test.CoolApplication'
    });
```

Perhaps try using `manifest/application` for the xpath instead?

**Comment by alexconstantin** [comment]
@mlynch Thank you! It's working as expected now. The problem was that I was not passing `manifest/application` for the xpath.

```
project.android?.getAndroidManifest().setAttrs('manifest/application', {
    'android:usesCleartextTraffic': 'true'
  });
```
