### ISSUE TITLE
Enable editing `.xcconfig` files or other key=value based files

### ISSUE THREAD

**Issue by leo-jnesis** [ionic-team/trapeze#95]
Hi guys ! Amazing job on this project, as always ❤️ 

We have a project which takes advantage of XCode Configuration Files to easily handle debug/release builds (https://developer.apple.com/documentation/xcode/adding-a-build-configuration-file-to-your-project)

I might have missed it in the docs, but it seems we can't update those kind of files.
I would imagine using it a bit like `json` where we would directly target the right property and set its value : 
```
  - file: ios/App/Configs/base.xcconfig
    set: 
      MARKETING_VERSION: 4.3.2
``` 

Thanks !

**Comment by mlynch** [comment]
Correct, these aren't supported yet but certainly fair game. I'll add this as a future enhancement idea. Thanks!

**Comment by mlynch** [comment]
This file format is simple but not really documented at all. More info here for future reference https://pewpewthespells.com/blog/xcconfig_guide.html

**Comment by mlynch** [comment]
Must have forgotten to close this because this was shipped a while back: https://trapeze.dev/docs/Operations/ios#xcconfig
